# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
x1 = torch.rand((7,7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
x2 = torch.rand((1,7))
x2_t = x2.t()
# Perform matrix multiplication
result = torch.matmul(x1, x2_t)
print(result,',', result.shape)


tensor([[1.6554],
        [0.9915],
        [1.1797],
        [1.1193],
        [1.3972],
        [1.2185],
        [1.2000]]) , torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
y1 = torch.rand((7,7))
y2 = torch.rand((1,7))
y2_t = y2.t()

# Matrix multiply tensors
result_2= torch.matmul(y1, y2_t)

print(result_2 ,',', result_2.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) , torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)

    # Create two random tensors on GPU
    t_1_gpu = torch.randn(2,3).cuda()
    t_2_gpu = torch.randn(2,3).cuda()

    print(t_1_gpu)
    print(t_2_gpu)



Device: cuda
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]], device='cuda:0')
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
matmul_gpu = torch.matmul(t_1_gpu, t_2_gpu.t())
matmul_gpu

tensor([[ 0.5595, -0.5087],
        [ 0.4036,  0.2792]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = torch.max(matmul_gpu)
print("Maximum value:", max_value)

# Find min
min_value = torch.min(matmul_gpu)
print("Minimum value:", min_value)


Maximum value: tensor(0.5595, device='cuda:0')
Minimum value: tensor(-0.5087, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_indices = torch.argmax(matmul_gpu)
max_row = max_indices // matmul_gpu.shape[1]
max_col = max_indices % matmul_gpu.shape[1]
print("Maximum index values:")
print("Row:", max_row.item(), "Column:", max_col.item())

# Find arg min
min_indices = torch.argmin(matmul_gpu)
min_row = min_indices // matmul_gpu.shape[1]
min_col = min_indices % matmul_gpu.shape[1]
print("Minimum index values:")
print("Row:", min_row.item(), "Column:", min_col.item())

Maximum index values:
Row: 0 Column: 0
Minimum index values:
Row: 0 Column: 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.randn(1, 1, 1, 10)

# Remove single dimensions
new_tensor = tensor.squeeze()

# Print out tensors and their shapes
print("Original Tensor:")
print(tensor, tensor.shape)

print("\nTensor after removing dimensions of size 1:")
print(new_tensor,new_tensor.shape)

Original Tensor:
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) torch.Size([1, 1, 1, 10])

Tensor after removing dimensions of size 1:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) torch.Size([10])
